### PR TITLE
Create updated-tools.js

### PR DESCRIPTION
**Pull request by ghost**
hackerexperience.com to legacy.hackerexperience.com

### CODE REVIEW

**Comment by lee8oi** [comment]
What's changed here? My copy already has the legacy url.

**Comment by ghost** [comment]
yea it did,but on the refresh of the log file,it loaded hackerexperience.com not legacy.hackerexperience.com, after making that edit, its working fine for me

**Comment by lee8oi** [comment]
Ok. Do you mind changing the original file instead of creating a new one? So I can see the changes? And thank you for the fix.

**Comment by ghost** [comment]
done :) new pull request

**Pull request closed without merging**
